project:
  project_name: "konecta-task9-gcp-project-3"
  project_id: "konecta-task9-gcp-project-id-3"
  organization_id: null
  billing_account: "XXXXXX-XXXXXX-XXXXXX"
  deletion_policy: "DELETE"
  labels:
    owner: intern
    environment: test
  apis:
    - compute.googleapis.com
    - iam.googleapis.com
vpc_name: "konecta-task9-vpc"
routes:
  - name: "konecta-task9-vpc-default-route"
    dest_range: "0.0.0.0/0"
    next_hop_gateway: "default-internet-gateway"
subnets:
  - name: "konecta-task9-pb-subnet"
    cidr: "10.0.1.0/24"
    region: "us-central1"
  - name: "konecta-task9-pv-subnet"
    cidr: "10.0.2.0/24"
    region: "us-central1"